Repository CaddyDz/Turbo, pull requests merged in 2020-06, with the labels that each got.

#131 Tested email verification closes #123
  .env.example
  app/Http/Controllers/HomeController.php
  app/Notifications/EmailVerificationNotification.php
  app/User.php
  composer.json
  composer.lock
  routes/web.php
  tests/Feature/EmailVerificationTest.php
Labels: enhancement, tests

#135 Link to static assets from the base URL
  resources/views/about.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header.blade.php
  resources/views/partials/mobile_menu.blade.php
  resources/views/partials/reviews.blade.php
  resources/views/partials/team.blade.php
Labels: UI

#141 Allow users to change their password
  app/Http/Controllers/AccountController.php
  app/Http/Requests/ChangePasswordRequest.php
  resources/lang/fr.json
  resources/views/auth/passwords/change.blade.php
  resources/views/dashboard.blade.php
  resources/views/partials/account_navigation.blade.php
  routes/web.php
  tests/Feature/ChangePasswordTest.php
Labels: enhancement

#144 100% code coverage
  .env.example
  .gitignore
  .styleci.yml
  app/Console/Kernel.php
  app/Http/Controllers/AccountController.php
  app/Http/Controllers/HomeController.php
  app/Http/Requests/ChangePasswordRequest.php
  app/Notifications/EmailVerificationNotification.php
  app/User.php
  composer.json
  composer.lock
  config/cache.php
  config/database.php
  config/filesystems.php
  config/ide-helper.php
  config/session.php
  database/factories/ProfileFactory.php
  database/helpers/ImageGenerator.php
  database/seeds/UserSeeder.php
  public/images/avatar.png
  public/images/avatar44x44.png
  resources/lang/fr.json
  resources/views/about.blade.php
  resources/views/auth/passwords/change.blade.php
  resources/views/dashboard.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header.blade.php
  resources/views/partials/account_navigation.blade.php
  resources/views/partials/mobile_menu.blade.php
  resources/views/partials/reviews.blade.php
  resources/views/partials/team.blade.php
  routes/web.php
  tests/CreatesApplication.php
  tests/Feature/ChangePasswordTest.php
  tests/Feature/EmailVerificationTest.php
  tests/Feature/ProfileTest.php
Labels: tests

#145 [skip ci] Added labeler workflow config
  .github/labeler.yml
  .github/workflows/label.yml
Labels: repo

#154 Users can change application language
  app/Http/Controllers/LocalizationController.php
  app/Http/Kernel.php
  app/Http/Middleware/Locale.php
  resources/lang/fr.json
  resources/views/layouts/topbar.blade.php
  resources/views/partials/languageSwitcher.blade.php
  tests/Feature/LocalizationTest.php
Labels: Localization, UI, UX, enhancement, tests

#157 Updated node dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript

#158 Updated laravel mix
  package.json
Labels: dependencies, javascript

#178 Moved post header and pre footer to block layout
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/change.blade.php
  resources/views/auth/passwords/confirm.blade.php
  resources/views/dashboard.blade.php
  resources/views/layouts/block.blade.php
  tests/Feature/ChangePasswordTest.php
Labels: CS, UI, tests

#181 Added media library prerequisites
  README.md
Labels: documentation

#182 Added dev route to test mailables
  app/Providers/RouteServiceProvider.php
  routes/dev.php
  tests/Feature/RoutesTest.php
Labels: UI, config, security, tests, wontfix

#184 Search
  .env.example
  .env.travis
  .gitignore
  app/Helpers.php
  app/Http/Controllers/PagesController.php
  app/Http/Controllers/SearchController.php
  app/Http/Requests/SearchRequest.php
  app/Part.php
  app/Vehicle.php
  composer.json
  composer.lock
  config/horizon.php
  config/scout.php
  database/factories/VehicleFactory.php
  database/migrations/2020_06_11_064253_create_vehicles_table.php
  resources/views/index.blade.php
  resources/views/parts/list_item.blade.php
  resources/views/search/results.blade.php
  resources/views/svg/arrow_up.blade.php
  resources/views/svg/chart.blade.php
  resources/views/svg/checked_filter.blade.php
  resources/views/svg/heart.blade.php
  resources/views/svg/zoom.blade.php
  routes/web.php
  storage/debugbar/.gitignore
  tests/Feature/ExampleTest.php
  tests/Feature/LocalizationTest.php
  tests/Feature/SearchTest.php
Labels: UI, UX, config, enhancement, repo, tests

#185 Added chrome debugger config
  .vscode/launch.json
  app/Http/Controllers/SearchController.php
  tests/Feature/SearchTest.php
Labels: CS, tests

#186 Closes #136
  .env.travis
  resources/views/auth/login.blade.php
  resources/views/partials/account_menu.blade.php
  resources/views/partials/account_navigation.blade.php
  tests/Feature/SearchTest.php
Labels: UI

#183 Readme
  README.md
Labels: documentation, repo

#190 patch-419
  resources/views/errors/419.blade.php
Labels: UI

#192 Created a 419 page expired error page
  resources/lang/fr.json
  resources/views/contact.blade.php
  resources/views/errors/419.blade.php
Labels: Localization, UI, security

#193 Fixed error resending verification email
  .env.example
  resources/lang/fr/validation.php
  resources/views/auth/register.blade.php
  resources/views/auth/verify.blade.php
Labels: UI, security

#195 Dynamic app settings
  .gitignore
  app/Providers/AppServiceProvider.php
  app/Providers/NovaServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  config/nova-translatable.php
  config/nova.php
  config/novapage.php
  resources/lang/fr.json
  resources/lang/option/header.json
  resources/views/layouts/header.blade.php
  resources/views/layouts/topbar.blade.php
  resources/views/svg/arrow_down.blade.php
Labels: Localization, UI, config, enhancement, repo

#196 Horizon queues dashboard config
  .gitignore
  .travis.yml
  app/Console/Kernel.php
  app/Nova/Option.php
  app/Nova/Resource.php
  app/Nova/Templates/HeaderOptions.php
  app/Nova/User.php
  app/Observers/PartObserver.php
  app/Observers/ProfileObserver.php
  app/Providers/AppServiceProvider.php
  app/Providers/HorizonServiceProvider.php
  app/Providers/NovaServiceProvider.php
  app/Providers/ObserverServiceProvider.php
  config/app.php
  config/nova-translatable.php
  config/nova.php
  config/novapage.php
Labels: config, repo

#197 Added search assets
  .gitignore
  app/Http/Controllers/BrandsController.php
  app/Http/Controllers/VehiclesController.php
  app/Http/Requests/BrandModelsRequest.php
  app/Http/Requests/ModelFuelOptionsRequest.php
  app/Http/Requests/YearsBrandRequest.php
  public/css/style.css
  public/js/main.js
  public/js/search.js
  routes/api.php
Labels: repo

#198 Seed database
  .gitignore
  database/factories/PartFactory.php
  database/migrations/2020_06_11_114134_create_parts_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/UserSeeder.php
  database/seeds/VehicleSeeder.php
Labels: repo

#199 Dark theme for exceptions and open in VSCode
  config/ignition.php
Labels: config

#202 Customize file paths
  app/CustomPathGenerator.php
  config/media-library.php
  database/seeds/DatabaseSeeder.php
Labels: config

#205 Added signature invalid error page
  resources/lang/fr.json
  resources/views/errors/403.blade.php
  resources/views/partials/account_menu.blade.php
  routes/dev.php
Labels: UI

#206 Drying header
  .env.example
  .gitignore
  .travis.yml
  app/Category.php
  app/Providers/AppServiceProvider.php
  app/Type.php
  composer.json
  database/factories/CategoryFactory.php
  database/factories/PartFactory.php
  database/factories/ProfileFactory.php
  database/factories/TypeFactory.php
  database/migrations/2020_06_10_125311_create_categories_table.php
  database/migrations/2020_06_10_125324_create_types_table.php
  database/migrations/2020_06_11_114134_create_parts_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/VehicleSeeder.php
  package-lock.json
  package.json
  public/css/app.css
  public/css/style.css
  public/css/style.header-classic-variant-five.css
  public/css/style.header-spaceship-variant-one.css
  resources/js/app.js
  resources/js/components/HeaderSearch.vue
  resources/js/components/svg-car.vue
  resources/js/components/svg-magnifier.vue
  resources/js/components/svg-trash.vue
  resources/js/locales.js
  resources/lang/fr.json
  resources/views/layouts/app.blade.php
  resources/views/layouts/header.blade.php
  resources/views/layouts/header/indicators.blade.php
  resources/views/layouts/header/logo.blade.php
  resources/views/layouts/header/navbar.blade.php
  resources/views/layouts/header/search.blade.php
  resources/views/layouts/header/topbar.blade.php
  resources/views/layouts/topbar.blade.php
  resources/views/partials/account_menu.blade.php
  resources/views/partials/languageSwitcher.blade.php
  resources/views/partials/mobile_menu.blade.php
  resources/views/search/results.blade.php
  resources/views/svg/account.blade.php
  resources/views/svg/arrow_right.blade.php
  resources/views/svg/button_arrow.blade.php
  resources/views/svg/cart.blade.php
  resources/views/svg/remove.blade.php
  resources/views/svg/sidebar.blade.php
  resources/views/svg/wish.blade.php
  resources/views/wishlist.blade.php
  routes/web.php
  webpack.mix.js
Labels: Localization, config, repo

#209 Instant search in header
  app/Http/Controllers/PartsController.php
  database/seeds/VehicleSeeder.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/js/components/HeaderSearch.vue
  resources/lang/fr.json
  routes/web.php
Labels: Localization

#216 Extract SVG icons markup to reusable Blade partial
  .env.example
  .gitignore
  phpunit.xml
  resources/views/index.blade.php
  resources/views/svg/arrow_left.blade.php
  resources/views/svg/free_shipping.blade.php
  resources/views/svg/hot_offers.blade.php
  resources/views/svg/phone_24x7.blade.php
  resources/views/svg/secure_payments.blade.php
  resources/views/svg/shop_circle.blade.php
  resources/views/svg/valid.blade.php
Labels: UI

#220 Header shopping cart
  .gitignore
  .travis.yml
  app/Http/Controllers/CartController.php
  app/Http/Controllers/PagesController.php
  app/Part.php
  app/Providers/AppServiceProvider.php
  database/factories/CategoryFactory.php
  database/factories/PartFactory.php
  database/migrations/2020_06_10_125311_create_categories_table.php
  database/migrations/2020_06_11_114134_create_parts_table.php
  database/seeds/CategorySeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/PartSeeder.php
  database/seeds/TypeSeeder.php
  database/seeds/VehicleSeeder.php
  resources/lang/fr.json
  resources/views/cart.blade.php
  resources/views/index.blade.php
  resources/views/layouts/header/cart.blade.php
  resources/views/layouts/header/indicators.blade.php
  resources/views/partials/featured.blade.php
  resources/views/partials/features.blade.php
  resources/views/partials/finder.blade.php
  resources/views/svg/X.blade.php
  routes/web.php
Labels: Localization, UI, repo

#221 Fixed sidebar images
  .gitignore
  resources/views/layouts/header/navbar.blade.php
Labels: repo

#222 Link to secure assets
  .gitignore
  resources/views/layouts/app.blade.php
  resources/views/parts/list_item.blade.php
Labels: repo

#224 Admin config
  .env.example
  .gitignore
  app/Providers/HorizonServiceProvider.php
  app/Providers/NovaServiceProvider.php
  config/nova.php
Labels: config, repo

#230 Work In Progress
  .travis.yml
  app/Category.php
  app/Providers/AppServiceProvider.php
  composer.json
  database/factories/CategoryFactory.php
  database/seeds/CategorySeeder.php
  database/seeds/PartSeeder.php
  database/seeds/TypeSeeder.php
  public/css/header-rtl.css
  public/css/header.css
  public/css/mobile-header.css
  public/css/rtl.css
  public/css/style.header-classic-variant-five.css
  public/css/style.header-classic-variant-four.css
  public/css/style.header-classic-variant-one.css
  public/css/style.header-classic-variant-three.css
  public/css/style.header-classic-variant-two.css
  public/css/style.header-spaceship-variant-three.css
  public/css/style.header-spaceship-variant-two.css
  public/css/style.mobile-header-variant-two.css
  public/js/search.js
  resources/js/components/HeaderSearch.vue
  resources/lang/fr.json
  resources/lang/option/header.json
  resources/views/cart.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header/cart.blade.php
  resources/views/layouts/header/navbar.blade.php
Labels: Localization, UI

#231 mobile svgs
  app/Part.php
  resources/lang/fr.json
  resources/views/errors/403.blade.php
  resources/views/index.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/layouts/header/logo.blade.php
  resources/views/layouts/mobile_header.blade.php
  resources/views/partials/mobile_menu.blade.php
  resources/views/svg/car.blade.php
  resources/views/svg/mobile/arrow_left.blade.php
  resources/views/svg/mobile/arrow_right.blade.php
  resources/views/svg/mobile/avatar.blade.php
  resources/views/svg/mobile/car.blade.php
  resources/views/svg/mobile/close_x.blade.php
  resources/views/svg/mobile/heart.blade.php
  resources/views/svg/mobile/menu_button.blade.php
  resources/views/svg/mobile/search.blade.php
  resources/views/svg/mobile/shop_circle.blade.php
  resources/views/svg/mobile/shopping.blade.php
  resources/views/svg/mobile_24x7.blade.php
  resources/views/svg/search.blade.php
Labels: UI

#235 [ci skip] Enabled CSRF and unicode in contact form
  resources/views/contact.blade.php
Labels: UI

#239 Create and show parts
  .env.example
  .github/labeler.yml
  app/Http/Controllers/PagesController.php
  app/Http/Controllers/PartsController.php
  app/Http/Controllers/TypesController.php
  app/Observers/PartObserver.php
  app/Part.php
  app/Profile.php
  app/Providers/HorizonServiceProvider.php
  app/Providers/NovaServiceProvider.php
  app/User.php
  config/site.php
  database/factories/PartFactory.php
  database/migrations/2020_06_11_114134_create_parts_table.php
  database/seeds/UserSeeder.php
  public/css/index.css
  public/css/style.css
  public/js/main.js
  resources/lang/fr.json
  resources/views/dashboard.blade.php
  resources/views/garage.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partials/account_menu.blade.php
  resources/views/partials/account_navigation.blade.php
  resources/views/partials/features.blade.php
  resources/views/partials/finder.blade.php
  resources/views/partials/new_arrivals.blade.php
  resources/views/svg/trash.blade.php
  routes/api.php
  routes/web.php
Labels: Localization, UI, config, repo

#245 Added Words to fr.json
  resources/lang/fr.json
  resources/views/index.blade.php
  resources/views/partials/features.blade.php
  resources/views/partials/mobile_menu_indicators.blade.php
  resources/views/svg/mobile/shop_circle.blade.php
Labels: Localization

#247 alt="" shit
  resources/views/about.blade.php
  resources/views/cart.blade.php
  resources/views/index.blade.php
  resources/views/partials/reviews.blade.php
  resources/views/partials/team.blade.php
  resources/views/search/results.blade.php
  resources/views/wishlist.blade.php
Labels: UI

#248 Link to categories and types
  app/Category.php
  app/Helpers.php
  app/Http/Controllers/CategoriesController.php
  app/Http/Controllers/PagesController.php
  app/Http/Controllers/TypesController.php
  app/Observers/CategoryObserver.php
  app/Observers/PartObserver.php
  app/Observers/TypeObserver.php
  app/Part.php
  app/Providers/AppServiceProvider.php
  app/Providers/ObserverServiceProvider.php
  app/Type.php
  composer.json
  database/factories/CategoryFactory.php
  database/factories/PartFactory.php
  database/factories/TypeFactory.php
  database/migrations/2020_06_10_125311_create_categories_table.php
  database/migrations/2020_06_10_125324_create_types_table.php
  database/seeds/DatabaseSeeder.php
  resources/lang/fr.json
  resources/views/category.blade.php
  resources/views/index.blade.php
  resources/views/layouts/breadcrumb.blade.php
  resources/views/layouts/header/megamenu.blade.php
  resources/views/layouts/header/navbar.blade.php
  resources/views/partials/brands.blade.php
  resources/views/partials/category_featured.blade.php
  resources/views/partials/featured.blade.php
  resources/views/svg/arrow_next.blade.php
  resources/views/svg/arrow_prev.blade.php
  routes/web.php
Labels: Localization, UI

#249 static assets
  resources/views/cart.blade.php
  resources/views/search/results.blade.php
  resources/views/wishlist.blade.php
Labels: UI

#252 Show parts created by auth user in admin panel
  app/Nova/Part.php
Labels: admin, enhancement

#254 Localize admin panel
  .github/labeler.yml
  app/Nova/Part.php
  app/Nova/Supplier.php
  app/Nova/User.php
  composer.json
  composer.lock
  resources/lang/fr.json
Labels: Localization, admin, repo

#264 Medanis98 footer options
  app/Nova/Templates/FooterOptions.php
  app/Providers/AppServiceProvider.php
  resources/lang/fr.json
  resources/lang/option/footer.json
  resources/views/layouts/footer.blade.php
Labels: Localization

#265 Added docs blocks to models
  app/Category.php
  app/Order.php
  app/Part.php
  app/Profile.php
  app/Supplier.php
  app/Type.php
  app/User.php
  app/Vehicle.php
Labels: CS, documentation

#266 Use tabs for indentation, globally
  .editorconfig
  .gitignore
  .php_cs
  phpcs.xml
  public/index.php
  resources/js/bootstrap.js
  resources/js/components/HeaderSearch.vue
  resources/lang/option/footer.json
  resources/views/about.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partials/add_vehicle_modal.blade.php
  resources/views/partials/photoswipe.blade.php
  resources/views/partials/reviews.blade.php
  resources/views/partials/team.blade.php
  resources/views/partials/vehicle_picker_modal.blade.php
  resources/views/search/results.blade.php
  resources/views/svg/arrow_left.blade.php
  resources/views/svg/car.blade.php
  resources/views/svg/free_shipping.blade.php
  resources/views/svg/hot_offers.blade.php
  resources/views/svg/mobile/account.blade.php
  resources/views/svg/mobile/arrow_left.blade.php
  resources/views/svg/mobile/arrow_right.blade.php
  resources/views/svg/mobile/car.blade.php
  resources/views/svg/mobile/close_x.blade.php
  resources/views/svg/mobile/heart.blade.php
  resources/views/svg/mobile/search.blade.php
  resources/views/svg/mobile/shopping.blade.php
  resources/views/svg/mobile_24x7.blade.php
  resources/views/svg/search.blade.php
  resources/views/svg/secure_payments.blade.php
  resources/views/svg/shop_circle.blade.php
  server.php
Labels: UI, repo

#267 Soft delete part model
  app/Nova/Part.php
  app/Part.php
  database/migrations/2020_06_11_114134_create_parts_table.php
Labels: admin

#271 Replacing jQuery wth vue.js
  public/js/main.js
  resources/js/app.js
  resources/js/components/LanguageSwitcher.vue
  resources/js/components/svg-arrow-down.vue
  resources/views/layouts/header.blade.php
  resources/views/layouts/header/search.blade.php
  resources/views/layouts/header/topbar.blade.php
  resources/views/partials/languageSwitcher.blade.php
Labels: UI

#277 Work In Progress
  app/Http/Controllers/InvoiceController.php
  app/Http/Controllers/ReceiptController.php
  app/Invoice.php
  app/InvoicePart.php
  app/Nova/Invoice.php
  app/Nova/Option.php
  app/Nova/Part.php
  app/Nova/Receipt.php
  app/Observers/InvoiceObserver.php
  app/Part.php
  app/Providers/ObserverServiceProvider.php
  app/Receipt.php
  composer.json
  composer.lock
  database/migrations/2020_06_24_204748_create_invoices_table.php
  database/migrations/2020_06_24_204810_create_receipts_table.php
  database/migrations/2020_06_25_095056_create_invoice_part_table.php
  resources/lang/fr.json
Labels: Localization, admin

#286 Create categories and types from admin panel
  app/Category.php
  app/Nova/Category.php
  app/Nova/Type.php
  app/Observers/TypeObserver.php
  app/Type.php
  public/css/header.css
  resources/lang/fr.json
  resources/views/layouts/header/megamenu.blade.php
  resources/views/layouts/header/navbar.blade.php
Labels: Localization, admin

#291 car brands
  database/seeds/data/brands.php
Labels: UI
