Repository CaddyDz/Turbo, pull requests merged in 2020-09, with the labels that each got.

#432 added parts to wishlist
  app/Facades/Wishlist.php
  app/Facades/WishlistFacade.php
  app/Http/Controllers/PartsController.php
  app/Http/Controllers/WishlistController.php
  app/Part.php
  app/Providers/AppServiceProvider.php
  config/app.php
  database/migrations/2020_06_11_114134_create_parts_table.php
  resources/views/part.blade.php
  resources/views/partials/part_card.blade.php
  resources/views/wishlist.blade.php
  routes/web.php
Labels: UI, database, enhancement, help wanted

#463 Add part to cart by quantity
  .env.example
  app/Http/Controllers/CartController.php
  app/Http/Controllers/NewsletterController.php
  app/Nova/Part.php
  app/Providers/AppServiceProvider.php
  composer.lock
  package-lock.json
  package.json
  public/css/header-rtl.css
  public/css/rtl.css
  public/css/style.css
  public/js/number.js
  resources/js/bootstrap.js
  resources/js/components/PartQuantityUpdate.vue
  resources/views/layouts/header/cart.blade.php
  resources/views/part.blade.php
Labels: UI, UX, javascript

#460 Test vehicle model route
  .travis.yml
  app/Http/Controllers/CartController.php
  database/factories/VehicleModelFactory.php
  tests/Feature/CatalogModelTest.php
Labels: database, tests

#465 Fix part price update in admin
  app/Nova/Part.php
  app/Observers/PartObserver.php
  app/Part.php
Labels: admin

#466 Use scout for nova only if available
  app/Nova/Resource.php
Labels: admin

#467 Cart quantity update feedback
  .github/workflows/label.yml
  app/Facades/Wishlist.php
  app/Http/Controllers/CartController.php
  app/Http/Controllers/WishlistController.php
  package-lock.json
  package.json
  public/css/header-rtl.css
  public/css/rtl.css
  public/css/style.css
  resources/js/app.js
  resources/js/bootstrap.js
  resources/js/components/PartQuantityUpdate.vue
  resources/views/layouts/mobile_header.blade.php
  resources/views/part.blade.php
  resources/views/partials/mobile_menu.blade.php
  resources/views/partials/rating.blade.php
  resources/views/svg/mobile/close_x.blade.php
  resources/views/wishlist.blade.php
  routes/web.php
  tests/Feature/WishlistTest.php
Labels: javascript

#471 Fixed bug when creating clients from admin panel
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientsController.php
  app/Observers/ClientObserver.php
  app/Providers/AppServiceProvider.php
  app/Providers/ObserverServiceProvider.php
  tests/Feature/ClientTest.php
Labels: UI, admin, bug, php, tests

#474 localized blade strings
  resources/views/about.blade.php
  resources/views/brand.blade.php
  resources/views/garage.blade.php
  resources/views/part.blade.php
  resources/views/pricing.blade.php
  resources/views/wishlist.blade.php
Labels: Localization, UI

#478 Catalog categories
  app/Http/Controllers/BrandsController.php
  tests/Feature/BrandTest.php
Labels: database, tests

#530 Alpha release
  .github/dependabot.yml
  app/Http/Controllers/BrandsController.php
  app/Http/Controllers/PartsController.php
  app/Http/Controllers/VehiclesController.php
  app/Nova/Client.php
  app/Providers/NovaServiceProvider.php
  composer.json
  composer.lock
  config/nova.php
  database/factories/ClientFactory.php
  database/migrations/2020_06_22_165956_create_suppliers_table.php
  database/migrations/2020_07_04_111656_create_clients_table.php
  database/seeds/RoleSeeder.php
  database/seeds/catalog/CategorySeeder.php
  database/seeds/catalog/EngineSeeder.php
  database/seeds/catalog/VehicleSeeder.php
  package-lock.json
  public/css/custom.css
  public/css/finder.css
  public/css/style.css
  public/js/finder.js
  public/js/main.js
  public/js/shop.js
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/brand.blade.php
  resources/views/dashboard.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header/search.blade.php
  resources/views/partials/account_menu.blade.php
  resources/views/partials/account_navigation.blade.php
  resources/views/partials/index/finder.blade.php
  resources/views/profile.blade.php
  resources/views/shop.blade.php
  routes/api.php
  routes/web.php
Labels: UI, admin, config, repo

#571 Linked Contact-us button
  resources/views/faq.blade.php
Labels: UI, help wanted
