Repository CaddyDz/Turbo, pull requests merged in 2020-07, with the labels that each got.

#298 Workshops and shops
  app/Category.php
  app/Http/Controllers/PartsController.php
  app/Http/Controllers/TypesController.php
  app/Http/Controllers/WorkshopController.php
  app/User.php
  app/Workshop.php
  database/migrations/2020_07_03_154307_create_workshops_table.php
  resources/views/layouts/header/navbar.blade.php
  resources/views/partials/account_menu.blade.php
  resources/views/partials/account_navigation.blade.php
  resources/views/partials/mobile_menu_indicators.blade.php
  resources/views/partials/mobile_menu_links.blade.php
  resources/views/shop.blade.php
  routes/web.php
Labels: UI

#311 Part view
  app/Part.php
  resources/lang/fr.json
  resources/views/part.blade.php
  resources/views/svg/magnifier.blade.php
Labels: Localization, UI

#316 Localize brands countries
  database/seeds/data/brands.php
  resources/lang/ar.json
  resources/lang/en.json
  resources/lang/fr.json
Labels: Localization

#320 VAT on client receipt
  app/Nova/Receipt.php
  app/Receipt.php
  database/migrations/2020_07_04_111657_create_receipts_table.php
  resources/lang/fr.json
  resources/views/print/receipt.blade.php
Labels: Localization, admin, database

#322 Search receipt by client and invoice by supplier
  app/Nova/Invoice.php
  app/Nova/Receipt.php
  app/Nova/Resource.php
  composer.json
  composer.lock
Labels: admin

#323 Allow users to review parts
  .gitignore
  app/Http/Controllers/PartsController.php
  app/Http/Controllers/ReviewsController.php
  app/Http/Requests/ReviewPartRequest.php
  app/Observers/ReviewObserver.php
  app/Part.php
  app/Providers/ObserverServiceProvider.php
  app/Review.php
  database/factories/ReviewFactory.php
  database/migrations/2020_07_06_135952_create_reviews_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ReviewSeeder.php
  resources/lang/fr.json
  resources/views/auth/login.blade.php
  resources/views/part.blade.php
  resources/views/partials/part/reviews.blade.php
  resources/views/vendor/pagination/.gitignore
  resources/views/vendor/pagination/bootstrap-4.blade.php
  routes/web.php
Labels: Localization, UI, database, enhancement, repo

#324 Removed duplicate SVG
  resources/views/brand.blade.php
  resources/views/category.blade.php
  resources/views/partials/category_featured.blade.php
  resources/views/svg/arrow_next.blade.php
  resources/views/svg/arrow_prev.blade.php
Labels: CS, UI

#325 Added key features to parts
  app/Http/Controllers/PartsController.php
  app/Http/Requests/StorePartRequest.php
  app/Nova/Part.php
  app/Part.php
  database/factories/PartFactory.php
  database/migrations/2020_06_11_114134_create_parts_table.php
  resources/js/app.js
  resources/js/components/KeyFeatures.vue
  resources/lang/fr.json
  resources/views/layouts/app.blade.php
  resources/views/part.blade.php
  resources/views/shop.blade.php
Labels: Localization, UI, admin

#326 Added excerpt to parts
  app/Observers/PartObserver.php
  database/factories/PartFactory.php
  database/migrations/2020_06_11_114134_create_parts_table.php
  resources/views/part.blade.php
Labels: UI

#330 Review updates
  app/Http/Controllers/PartsController.php
  config/app.php
  database/factories/ReviewFactory.php
  database/seeds/ReviewSeeder.php
Labels: config

#337 Discount base architeture
  app/Discount.php
  app/Http/Controllers/DiscountController.php
  app/Nova/Discount.php
  app/Policies/DiscountPolicy.php
  database/factories/DiscountFactory.php
  database/migrations/2020_07_13_085420_create_discounts_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/DiscountSeeder.php
Labels: admin

#338 translate admin panel
  app/Nova/Discount.php
  resources/lang/fr.json
Labels: Localization

#351 Show brands in admin panel
  app/Nova/Brand.php
  app/Nova/Vehicle.php
  database/factories/VehicleFactory.php
  database/migrations/2020_06_11_064253_create_vehicles_table.php
  database/seeds/UserSeeder.php
  database/seeds/data/brands.php
  resources/lang/fr.json
Labels: Localization, admin

#352 Manage roles and permissions via admin panel
  app/Nova/User.php
  app/Providers/NovaServiceProvider.php
  config/nova.php
  database/seeds/RoleSeeder.php
  database/seeds/UserSeeder.php
Labels: admin, config

#353 Personal stock
  app/Http/Controllers/StockController.php
  app/Nova/Stock.php
  app/Observers/PartObserver.php
  app/Policies/StockPolicy.php
  app/Stock.php
  app/User.php
  config/ide-helper.php
  database/factories/StockFactory.php
  database/migrations/2020_07_17_080240_create_stocks_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/StockSeeder.php
Labels: admin, config

#362 Import parts by excel
  app/Nova/Part.php
  app/Observers/PartObserver.php
  app/Stock.php
  composer.json
  composer.lock
  resources/lang/fr.json
Labels: Localization, admin

#365 Update profile info
  app/Http/Controllers/ProfileController.php
  app/Http/Requests/UpdateProfileRequest.php
  app/Observers/UserObserver.php
  app/Providers/ObserverServiceProvider.php
  resources/views/partials/account_navigation.blade.php
  resources/views/profile.blade.php
  routes/web.php
Labels: UI

#367 Allow admin to modify part view count
  app/Http/Controllers/PartsController.php
  app/Nova/Actions/ChangePartViews.php
  app/Nova/Part.php
  app/Part.php
  config/nova.php
  database/factories/PartFactory.php
  database/seeds/RoleSeeder.php
  resources/lang/fr.json
Labels: Localization, admin, config

#368 Update stock from receipt and invoice
  app/Invoice.php
  app/InvoicePart.php
  app/Jobs/UpdateStockFromInvoice.php
  app/Jobs/UpdateStockFromReceipt.php
  app/Nova/Invoice.php
  app/Nova/Receipt.php
  app/Nova/Receipt/Part.php
  app/Observers/InvoiceObserver.php
  app/Observers/ReceiptObserver.php
  database/migrations/2020_06_25_095056_create_invoice_part_table.php
  resources/lang/fr.json
Labels: Localization, admin

#369 Localize features in the part view
  resources/views/part.blade.php
Labels: Localization

#371 Hide add part in shop view by default
  public/css/style.css
  resources/js/app.js
  resources/views/shop.blade.php
Labels: UI

#373 Contact Store
  app/Http/Controllers/MessagesController.php
  app/Http/Controllers/PartsController.php
  app/Http/Controllers/StoreContactController.php
  app/Http/Controllers/StoreController.php
  app/Http/Requests/ContactStoreRequest.php
  app/Jobs/UpdateStockFromReceipt.php
  app/Message.php
  app/Nova/Invoice.php
  app/Nova/Message.php
  app/Nova/Part.php
  app/Nova/Profile.php
  app/Nova/Receipt.php
  app/Nova/Receipt/Part.php
  app/Nova/Store.php
  app/Nova/StoreContact.php
  app/Nova/User.php
  app/Observers/StoreContactObserver.php
  app/Policies/StoreContactPolicy.php
  app/Policies/StorePolicy.php
  app/Providers/ObserverServiceProvider.php
  app/Store.php
  app/StoreContact.php
  app/User.php
  composer.json
  composer.lock
  database/factories/MessageFactory.php
  database/factories/PartFactory.php
  database/factories/StoreContactFactory.php
  database/factories/StoreFactory.php
  database/migrations/2020_07_19_135745_create_stores_table.php
  database/migrations/2020_07_19_171709_create_store_contacts_table.php
  database/migrations/2020_07_20_145418_create_messages_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/MessageSeeder.php
  database/seeds/StoreContactSeeder.php
  database/seeds/StoreSeeder.php
  public/css/rtl.css
  public/images/vendor/leaflet/dist/layers-2x.png
  public/images/vendor/leaflet/dist/layers.png
  public/images/vendor/leaflet/dist/marker-icon-2x.png
  public/images/vendor/leaflet/dist/marker-icon.png
  public/images/vendor/leaflet/dist/marker-shadow.png
  resources/lang/fr.json
  resources/views/partials/brands.blade.php
  resources/views/store/contact.blade.php
  tests/Feature/PartTest.php
Labels: UI, admin

#377 Link to store
  app/Http/Controllers/StoresController.php
  app/Observers/StoreObserver.php
  app/Part.php
  app/Policies/StoreContactPolicy.php
  app/Providers/AppServiceProvider.php
  app/Providers/ObserverServiceProvider.php
  app/Store.php
  app/User.php
  database/migrations/2020_07_19_135745_create_stores_table.php
  resources/views/part.blade.php
  resources/views/store/index.blade.php
  routes/web.php
Labels: UI

#379 Responsive inline relation modal
  composer.json
  composer.lock
  config/nova-theme-responsive.php
Labels: config

#380 Work In Progress
  app/Compatibility.php
  app/Http/Controllers/CompatibilityController.php
  app/Nova/Compatibility.php
  app/Nova/Part.php
  app/Observers/SupplierObserver.php
  app/Part.php
  app/Providers/ObserverServiceProvider.php
  app/Vehicle.php
  composer.json
  composer.lock
  database/migrations/2020_07_22_151701_create_part_vehicle_table.php
  database/seeds/Compatibility.php
  nova-components/NovaPreviewResource/.gitignore
  nova-components/NovaPreviewResource/composer.json
  nova-components/NovaPreviewResource/dist/css/field.css
  nova-components/NovaPreviewResource/dist/js/field.js
  nova-components/NovaPreviewResource/dist/mix-manifest.json
  nova-components/NovaPreviewResource/package.json
  nova-components/NovaPreviewResource/resources/js/components/IndexField.vue
  nova-components/NovaPreviewResource/resources/js/field.js
  nova-components/NovaPreviewResource/resources/sass/field.scss
  nova-components/NovaPreviewResource/src/FieldServiceProvider.php
  nova-components/NovaPreviewResource/src/NovaPreviewResource.php
  nova-components/NovaPreviewResource/webpack.mix.js
  package.json
Labels: admin

#381 Preview parts in index
  app/Nova/Part.php
  app/Part.php
  database/migrations/2020_06_22_165956_create_suppliers_table.php
  database/migrations/2020_07_22_151701_create_part_vehicle_table.php
  nova-components/NovaPreviewResource/dist/js/field.js
  nova-components/NovaPreviewResource/resources/js/components/IndexField.vue
  nova-components/NovaPreviewResource/src/NovaPreviewResource.php
Labels: admin

#382 Installed cashier
  .env.example
  app/User.php
  composer.json
  composer.lock
  database/migrations/2019_05_03_000001_create_customer_columns.php
  database/migrations/2019_05_03_000002_create_subscriptions_table.php
  database/migrations/2019_05_03_000003_create_subscription_items_table.php
Labels: config

#385 Garage interface
  app/Garage.php
  app/Http/Controllers/GarageController.php
  app/Nova/Message.php
  app/Observers/GarageObserver.php
  app/Policies/GaragePolicy.php
  app/Providers/ObserverServiceProvider.php
  app/User.php
  database/migrations/2020_07_25_123852_create_garages_table.php
  database/migrations/2020_07_25_141817_create_garage_vehicle_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/GarageSeeder.php
  resources/views/garage.blade.php
  resources/views/partials/account_navigation.blade.php
  resources/views/shop.blade.php
  routes/web.php
  tecdoc.md
Labels: UI, admin

#386 Pricing page
  public/css/pricing.css
  resources/views/pricing.blade.php
  routes/web.php
Labels: UI

#388 Store about page
  app/Http/Controllers/StoreAboutController.php
  app/Http/Resources/StoreAbout.php
  app/Nova/StoreAbout.php
  app/Nova/StoreContact.php
  app/Observers/StoreAboutObserver.php
  app/Policies/StoreAboutPolicy.php
  app/Providers/ObserverServiceProvider.php
  app/Store.php
  app/StoreAbout.php
  database/factories/StoreAboutFactory.php
  database/migrations/2020_07_26_144414_create_store_abouts_table.php
  database/seeds/StoreAboutSeeder.php
  public/css/style.css
  resources/views/store/about.blade.php
  resources/views/store/index.blade.php
  routes/web.php
  tests/Feature/StoreTest.php
Labels: admin, tests

#389 Remove images from part excel export
  app/Nova/Part.php
Labels: admin

#392 Allow addition of parts to receipts by reference
  .styleci.yml
  app/Nova/Receipt.php
  app/Nova/Receipt/Part.php
  database/factories/StockFactory.php
Labels: admin

#393 Use Place field for addresses
  app/Nova/Client.php
  app/Nova/Supplier.php
  app/Nova/Templates/FooterOptions.php
Labels: admin

#394 Separate (create a new receipt) one with client and one without
  app/Nova/Bill.php
  app/Nova/Receipt.php
  database/seeds/ClientSeeder.php
  resources/lang/fr.json
Labels: Localization, admin
